[package]
name = "mandelbrot-simd-rs"
version = "0.1.0"
authors = ["chamatht"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packed_simd = "0.3.3"
png = "0.15.3"

[profile.release]
lto=true
opt-level=2
#debug=true
